**Membaca Karakter Khusus Pada Kalimat Pada Variabel Data Yang Diisi Dengan Data Frame**

Pada hasil data di bawah ini masih terdapat duplikasi symbol pada masing-masing baris kalimat....::

In [15]:
import pandas as pd
import re

# membuat dataframe contoh
data = {'Tweet': ['Ini adalah tweet pertama! #contoh', 'Ini adalah tweet kedua. :)', 'Ini adalah tweet ketiga, dengan 12345.']}
dfx = pd.DataFrame(data)

#  Membuat lits global untuk menampilkan hasilnya ke samping 
result = []

# mencari karakter khusus selain huruf dan angka pada kolom Tweet dan menghilangkan duplikasinya
karakter_khusus = set()
for tweet in dfx['Tweet']:
    # mencari karakter yang bukan huruf atau angka dalam tweet
    karakter_khusus_tweet = re.findall(r'[^a-zA-Z0-9\s]', tweet)
    # menambahkan karakter khusus pada tweet ke dalam set karakter khusus
    karakter_khusus.update(karakter_khusus_tweet)

# menampilkan karakter khusus yang ditemukan
print("Karakter khusus yang ditemukan:")
for karakter in karakter_khusus:
    list.append(karakter_khusus)
print(list)

Karakter khusus yang ditemukan:
[{'#', '.', ')', ',', '!', ':'}, {'#', '.', ')', ',', '!', ':'}, {'#', '.', ')', ',', '!', ':'}, {'#', '.', ')', ',', '!', ':'}, {'#', '.', ')', ',', '!', ':'}, {'#', '.', ')', ',', '!', ':'}]

**Berikut ini kode yang hasil pencariannya tidak terjadi duplikasi simbol**

In [16]:
import pandas as pd
import re

# membuat dataframe contoh
data = {'Tweet': ['Ini adalah tweet pertama! #contoh', 'Ini adalah tweet kedua. :)', 'Ini adalah tweet ketiga, dengan 12345.']}
dfx = pd.DataFrame(data)

#  Membuat list global untuk menampilkan hasilnya ke samping 
result = []

# mencari karakter khusus selain huruf dan angka pada kolom Tweet dan menghilangkan duplikasinya
karakter_khusus = set()

for tweet in dfx['Tweet']:
    # mencari karakter yang bukan huruf atau angka dalam tweet
    karakter_khusus_tweet = re.findall(r'[^a-zA-Z0-9\s]', tweet)
    # menambahkan karakter khusus pada tweet ke dalam set karakter khusus
    karakter_khusus.update(karakter_khusus_tweet)

# menampilkan karakter khusus yang ditemukan
print("Karakter khusus yang ditemukan:")
for karakter in karakter_khusus:
    result.append(karakter)
    
print(result)

Karakter khusus yang ditemukan:
['#', '.', ')', ',', '!', ':']

**Bagaimana Jika Data Itu Ada Di Dalam Database?**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
%cd /content/drive/MyDrive/Colab Notebooks/BINAR GOLD CHALLANGE

/content/drive/MyDrive/Colab Notebooks/BINAR GOLD CHALLANGE

In [17]:
df = pd.read_csv('data.csv', encoding='latin-1')

In [18]:
df[['Tweet']]

                                                   Tweet
0      - disaat semua cowok berusaha melacak perhatia...
1      RT USER: USER siapa yang telat ngasih tau elu?...
2      41. Kadang aku berfikir, kenapa aku tetap perc...
3      USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...
4      USER USER Kaum cebong kapir udah keliatan dong...
...                                                  ...
13164  USER jangan asal ngomong ndasmu. congor lu yg ...
13165                       USER Kasur mana enak kunyuk'
13166  USER Hati hati bisu :( .g\n\nlagi bosan huft \...
13167  USER USER USER USER Bom yang real mudah terdet...
13168  USER Mana situ ngasih(": itu cuma foto ya kuti...

[13169 rows x 1 columns]

In [19]:
import pandas as pd
import re

#  Membuat list global untuk menampilkan hasilnya ke samping 
result = []

# mencari karakter khusus selain huruf dan angka pada kolom Tweet dan menghilangkan duplikasinya
karakter_khusus = set()

for tweet in df['Tweet']:
    # mencari karakter yang bukan huruf atau angka dalam tweet
    karakter_khusus_tweet = re.findall(r'[^a-zA-Z0-9\s]', tweet)
    # menambahkan karakter khusus pada tweet ke dalam set karakter khusus
    karakter_khusus.update(karakter_khusus_tweet)

# menampilkan karakter khusus yang ditemukan
print("Karakter khusus yang ditemukan:")
for karakter in karakter_khusus:
    result.append(karakter)
    
print(result)

Karakter khusus yang ditemukan:
['>', 'Â¸', 'Âª', 'Â¨', '/', '_', 'Ã‚', 'Â±', '\\', '=', 'Â³', 'Ã¡', '*', ':', '|', 'Â¥', 'Ã¯', 'Â«', 'Â²', '`', 'Ã„', 'Â»', '}', '.', 'Â°', '%', 'Ã«', "'", 'Ã°', 'Â¢', 'Â¶', 'Âµ', 'Â·', '^', '-', '(', 'Â¡', 'Â®', 'Â£', ';', 'Â½', 'Â¬', '$', '#', 'Ã˜', ')', 'Ã™', '?', '~', 'Ã¢', ']', 'Âº', 'Ãª', '!', 'Â¹', '&', 'Â©', '@', 'Â¦', '{', '\xad', 'Â¿', '[', 'Â¯', '"', ',', 'Â¼', 'Ãƒ', 'Â§', '+', 'Â´', 'Ã£', 'Â¤']